# Generated by Django 5.1.4 on 2025-06-18 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_isrclinksaudios_lyricfindregistro_clientes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isrclinksaudios',
            options={'managed': True, 'verbose_name': 'Link de Audio (ISRC)', 'verbose_name_plural': 'Links de Audio (ISRC)'},
        ),
        migrations.AlterModelOptions(
            name='lyricfindregistro',
            options={'managed': True, 'verbose_name': 'Registro LyricFind', 'verbose_name_plural': 'Registros LyricFind'},
        ),
    ]
