# Generated by Django 5.1.4 on 2025-08-20 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_legacyaccountuser_alter_user_options_clienteaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyStatementExcel',
            fields=[
                ('id_legacy', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_file', models.IntegerField()),
                ('work_writer_list', models.CharField(max_length=1000, null=True)),
                ('work_primary_title', models.CharField(max_length=500, null=True)),
                ('iswc', models.CharField(max_length=100, null=True)),
                ('usage_period_start', models.DateField(null=True)),
                ('usage_period_end', models.DateField(null=True)),
                ('use_type', models.CharField(max_length=100, null=True)),
                ('processing_type', models.CharField(max_length=100, null=True)),
                ('dsp_name', models.CharField(max_length=200, null=True)),
                ('number_of_usages', models.IntegerField(null=True)),
                ('distributed_amount_usd', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('row_idx', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'legacy_statements_excel',
                'indexes': [models.Index(fields=['id_file'], name='legacy_stat_id_file_f55d8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoyaltyStatement',
            fields=[
                ('id_statement', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_file', models.IntegerField()),
                ('derecho', models.CharField(choices=[('Mecanico', 'Mecanico'), ('MicroSync', 'MicroSync')], max_length=16)),
                ('anio', models.SmallIntegerField()),
                ('periodo_q', models.PositiveSmallIntegerField()),
                ('obra_id', models.IntegerField()),
                ('codigo_sgs', models.CharField(max_length=100)),
                ('codigo_mlc', models.CharField(max_length=100)),
                ('work_primary_title', models.CharField(max_length=500, null=True)),
                ('work_writer_list', models.CharField(max_length=1000, null=True)),
                ('iswc', models.CharField(max_length=100, null=True)),
                ('usage_period_start', models.DateField(null=True)),
                ('usage_period_end', models.DateField(null=True)),
                ('use_type', models.CharField(max_length=100, null=True)),
                ('processing_type', models.CharField(max_length=100, null=True)),
                ('dsp_name', models.CharField(max_length=200, null=True)),
                ('number_of_usages', models.IntegerField(null=True)),
                ('distributed_amount_usd', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('artist_name', models.CharField(max_length=255, null=True)),
                ('isrc', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'royalty_statements',
                'indexes': [models.Index(fields=['anio', 'periodo_q'], name='royalty_sta_anio_6666b8_idx'), models.Index(fields=['obra_id'], name='royalty_sta_obra_id_e0df6e_idx'), models.Index(fields=['codigo_mlc'], name='royalty_sta_codigo__fb4732_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatementFile',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('derecho', models.CharField(choices=[('Mecanico', 'Mecanico'), ('MicroSync', 'MicroSync')], max_length=16)),
                ('anio', models.SmallIntegerField()),
                ('periodo_q', models.PositiveSmallIntegerField()),
                ('file_type', models.CharField(choices=[('XLSX', 'XLSX'), ('TSV', 'TSV')], max_length=8)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('filas_cargadas', models.IntegerField(default=0)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.clientes')),
            ],
            options={
                'db_table': 'statement_files',
                'indexes': [models.Index(fields=['cliente', 'anio', 'periodo_q'], name='statement_f_cliente_74a22a_idx')],
            },
        ),
    ]
