# Generated by Django 5.1.4 on 2025-06-18 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_isrclinksaudios_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='isrclinksaudios',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='LyricfindRegistro',
            fields=[
                ('id_lyricfind', models.AutoField(primary_key=True, db_column='id_lyricfind', serialize=False)),
                ('lyric_text', models.TextField()),
                ('estado', models.CharField(max_length=10, choices=[('Pendiente', 'Pendiente'), ('Procesado', 'Procesado'), ('Error', 'Error')], default='Pendiente')),
                ('motivo_error', models.TextField(null=True, blank=True)),
                ('fecha_proceso', models.DateTimeField(auto_now_add=True, db_column='fecha_proceso')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('artista_unico', models.ForeignKey(db_column='id_artista_unico', on_delete=django.db.models.deletion.CASCADE, related_name='lyricfind_registros', to='accounts.artistasunicos')),
                ('isrc', models.ForeignKey(db_column='id_isrc', on_delete=django.db.models.deletion.CASCADE, related_name='lyricfind_registros', to='accounts.codigosisrc')),
                ('obra', models.ForeignKey(db_column='obra_id', on_delete=django.db.models.deletion.CASCADE, related_name='lyricfind_registros', to='accounts.obras')),
            ],
            options={
                'db_table': 'lyricfind_registros',
                'unique_together': {('obra', 'isrc', 'artista_unico')},
                'verbose_name': 'Registro LyricFind',
                'verbose_name_plural': 'Registros LyricFind',
                'managed': True,  # solo temporal mientras aplicamos esta migración
            },
        ),
    ]
