# Generated by Django 5.1.4 on 2025-08-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_legacystatementexcel_royaltystatement_statementfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legacystatementexcel",
            name="work_primary_title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="legacystatementexcel",
            name="work_writer_list",
            field=models.TextField(blank=True, null=True),
        ),
    ]
