# Generated by Django 5.1.4 on 2025-08-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_microsyncstatement_delete_legacymicrosyncexcel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microsyncmarketshare",
            name="amount_payable_usd",
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="microsyncstatement",
            name="amount_payable_usd",
            field=models.DecimalField(decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="microsyncstatement",
            name="asset_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="microsyncstatement",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="microsyncstatement",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
